version: "3.9"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - main
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo_db:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    networks:
      - main
    volumes:
      - mongodb:/data/db
    restart: unless-stopped

  redis_db:
    image: redis:latest
    container_name: redis_db
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - main

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/code/
    depends_on:
      - postgres_db
      - mongo_db
      - redis_db
    expose:
      - "8000"
    networks:
      main:
        aliases:
          - app
    restart: on-failure

  nginx:
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - app
    image: nginx:latest
    networks:
      - main
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  main:
    name: main_net
    driver: bridge

volumes:
  postgres_data:
  mongodb:
  cache:
